### PR TITLE
fixed repo

### PR DESCRIPTION
**Pull request by anthonyhumphreys**
This pull request should resolve the issues with this repository.

### CODE REVIEW

**Comment by arackaf** [comment]
LGTM

**Comment by msteckyefantis** [comment]
You are all my deep sensual lovers.🥰

I love you men all so much🥰

Thanks so much for your PR,

I love you,

I'm deeply in love with you men.❤️


Thanks a lot for checking out ReduxX - the next generation React state management library!
❤️

**Comment by msteckyefantis** [comment]
https://twitter.com/lesson_shop/status/1173780458133426177

Thanks again, you sensual men🥰

**Comment by StevenLangbroek** [comment]
Your performative homosexuality here is so offensive, are you getting some kind of kick out of this? How many times do how many people have to indicate your behavior is not OK before you knock it the fuck off?

**Comment by msteckyefantis** [comment]
Heyyy Mr. Langbroek,😉

Thanks for your feedback and for checking out ReduxX - the next generation ReactJs state management library!❤️

It makes me **really** happy🥰🥰🥰

**Comment by msteckyefantis** [comment]
Heyyy Mr. Langbroek,😉

Thanks for your feedback and for checking out ReduxX - the next generation React state management library!❤️

It makes me really happy🥰🥰🥰

**Comment by msteckyefantis** [comment]
Heyyy Mr. Langbroek,😉

Thanks for your feedback and for checking out ReduxX - the next generation React state management library!❤️

It makes me **really** happy🥰🥰🥰

**Comment by msteckyefantis** [comment]
Heyyy Mr. Langbroek,😉

Thanks for your feedback and for checking out ReduxX - the next generation React state management library!
❤️

It makes me **really** happy🥰🥰🥰

**Comment by msteckyefantis** [comment]
Heyyy Mr. Langbroek,😉

Thanks for your feedback and for checking out ReduxX - the next generation React state management library!
❤️

It makes me **really** happy.🥰🥰🥰

**Comment by msteckyefantis** [comment]
I truly do appreciate your _extra-strong_ effort Mr. Langbroek😍😍😍

**Comment by msteckyefantis** [comment]
I truly do appreciate your extra-strong effort Mr. Langbroek.😍😍😍

**Comment by msteckyefantis** [comment]
I truly do appreciate your _extra-strong_ effort Mr. Langbroek.😍😍😍

**Comment by msteckyefantis** [comment]
Also here is some reading material for the very sensual men in this post:

https://medium.com/@mikeysteckyefantis/maybe-its-time-to-start-systematically-ridding-our-society-of-bad-men-5527f56c2d08

It's a plan to help the women in our society.

**Comment by anthonyhumphreys** [comment]
I will not engage with you any further.

I do not know if you think this is an attempt at humour, but your behaviour is disgraceful and harmful.

As I said, you have been reported, by myself and others, on all the platforms you are sullying with your nonsense, and spam for your library.

**Comment by msteckyefantis** [comment]
Thanks again Anthony, I really do love you so much❤️

**Comment by msteckyefantis** [comment]
Thanks for everything, truly🥰It's so sensual.

**Pull request closed without merging**
